import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import TheSidebar from "@/components/layouts/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "UzComEx",
  description: "UzComEx is generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex relative h-screen overflow-y-auto">
          <TheSidebar />
          <main className="p-6 w-full md:ml-[260px]">{children}</main>
        </div>
      </body>
    </html>
  );
}
